import pandas as pd

def prompts_to_parquet(prompts, parquet_path):
    """
    Creates a parquet file with two columns:
      - image_name: auto-generated image name
      - prompt:     prompt text
    """

    df = pd.DataFrame({
        "image_name": [f"{i:04d}.png" for i in range(len(prompts))],
        "text": prompts
    })

    df.to_parquet(parquet_path, index=False)
    print(f"✅ Saved {len(df)} prompts to {parquet_path}")

prompts = [
    "The image is a photograph capturing a joyful scene in a lush, green outdoor setting. The atmosphere is bright and cheerful, with a focus on natural beauty and warmth. In the center of the image, there is a golden retriever lying on its stomach in a grassy field. The dog has a rich, golden coat that appears soft and well-groomed. Its tongue is playfully sticking out, and it has a wide, happy smile, suggesting a sense of contentment and joy. The dog is wearing a black harness, which is positioned snugly around its chest and back. The grass is vibrant green, dotted with small white flowers, adding a delicate touch to the scene. The flowers are scattered randomly across the field, creating a natural and unstructured pattern. The background is slightly blurred, indicating a shallow depth of field, which helps to keep the focus on the dog. This background blur also suggests a larger, open space, possibly a park or garden. The composition style is centered, with the dog positioned slightly off-center to the left, drawing the viewer's eye directly to its happy expression. The framing is natural, capturing the dog in its environment without any artificial boundaries. The dominant color tones are green from the grass and white from the flowers, with the golden hue of the dog's fur providing a warm contrast. The image has high saturation and brightness, enhancing the cheerful and lively mood. The sharpness is clear, particularly on the dog, while the background blur adds depth and focus to the subject. Overall, the image exudes warmth and happiness, with the golden retriever as the central, joyful character in a serene, natural setting.",
    "The image is a photograph capturing a serene and heartwarming scene. It features a small, white puppy lying on a wooden deck. The puppy has a soft, fluffy coat and large, expressive eyes that convey a sense of curiosity and innocence. Its ears are floppy and hang down on either side of its head, and it wears a green collar around its neck, adding a touch of color to its predominantly white fur. The puppy is positioned centrally in the frame, facing the camera directly, which draws the viewer's attention immediately to its adorable features. Its front paws are stretched out in front of it, while its hind legs are tucked under its body, giving it a relaxed and comfortable appearance. The background is softly blurred, creating a bokeh effect that highlights the puppy as the focal point. The blurred greenery suggests an outdoor setting, likely a garden or park, contributing to a peaceful and natural atmosphere. The lighting is bright and natural, indicating that the photo was taken during the day, possibly on a sunny afternoon. The composition style is simple yet effective, with the puppy placed centrally to create a balanced and engaging image. The color tones are warm and inviting, with a high saturation that enhances the puppy's white fur and the green collar. The background blur and the natural lighting add depth and a sense of tranquility to the scene. Overall, the image exudes warmth and cuteness, capturing a moment of innocent curiosity in a serene outdoor setting.",
    "The image is a photograph of a cheerful golden retriever puppy. The atmosphere is warm and inviting, with a soft, bright background that enhances the puppy's golden fur. The puppy is positioned centrally in the frame, sitting on a dark surface, likely a table or bench, which contrasts with its light fur. The puppy has a fluffy, golden coat with a slightly lighter shade on its chest and face. Its ears are floppy and hang down on either side of its head. The puppy's eyes are bright and expressive, and its mouth is open in a joyful smile, revealing its small pink tongue. The puppy's overall appearance is playful and endearing, exuding happiness and energy. The composition style is straightforward and focused, with the puppy being the sole subject of the image. The background is plain and light, ensuring that the puppy stands out prominently. The lighting is soft and even, highlighting the puppy's fur and giving it a gentle glow. The image has high saturation and brightness, with a slight blur in the background to keep the attention on the puppy. There is no discernible text in the image. The dominant color tones are warm, with golden and beige hues dominating the scene. The contrast between the puppy's fur and the dark surface it sits on adds depth to the image. The overall effect is a heartwarming and visually appealing photograph that captures the puppy's joyful demeanor.",
    "The image is a close-up photograph of a golden retriever dog. The atmosphere is warm and inviting, with a focus on the dog's joyful expression. The composition centers on the dog's face, capturing its features in sharp detail. The dog has a rich golden-brown coat, with slightly wavy fur that frames its face. Its black nose is prominent, and its tongue is playfully sticking out, suggesting a relaxed and happy demeanor. The dog's eyes are partially visible, adding to its friendly expression. The fur around its face is slightly tousled, indicating movement or playfulness. The background is blurred, using a shallow depth of field to keep the focus on the dog. This background appears to be an outdoor setting, possibly a patio or a backyard, with neutral tones that do not distract from the main subject. The lighting is natural, likely from sunlight, enhancing the warm color tones of the dog's fur. The image has high saturation and brightness, making the colors vivid and the details sharp. The framing is tight, focusing on the dog's head and upper neck, with a slight angle that gives a dynamic perspective. Overall, the image exudes a sense of warmth and happiness, capturing a candid moment of the dog's contentment. There are no discernible texts or additional characters in the image. The composition style is straightforward, emphasizing the dog's expressive features and joyful emotion.",
    "The image is a photograph capturing a lively and playful scene in a sunlit backyard. At the center of the frame, a young border collie is mid-run, with its front paws lifted off the ground and its ears perked up in excitement. Its coat is a striking mix of black and white, with a glossy shine that catches the sunlight. The dog's mouth is slightly open, revealing a pink tongue and a joyful expression that radiates energy. The grass beneath it is a lush, vibrant green, with scattered autumn leaves adding pops of orange and yellow to the scene. In the background, a wooden fence and a few tall trees provide a natural frame, softly blurred to keep the focus on the dog. The lighting is bright yet gentle, with the afternoon sun casting a warm glow across the entire image. The composition style is dynamic, capturing the dog in motion with a slight diagonal tilt, adding a sense of movement and life. The colors are rich and saturated, with sharp focus on the dog's face and fur, while the background blur enhances the feeling of depth. Overall, the image exudes joy, energy, and the carefree spirit of a dog enjoying a perfect day outdoors.",
    "The image is a heartwarming photograph of a small, tan-colored puppy sitting inside a rustic wicker basket. The puppy has large, round eyes that shine with curiosity and a tiny black nose that contrasts with its light fur. Its short, velvety coat is a warm sandy hue, with a faint white patch on its chest. The puppy's ears are slightly floppy, tilting outward in an endearing way. The basket rests on a soft, cream-colored blanket, adding to the cozy feel of the scene. The background is softly lit, with a blurred arrangement of flowers in pastel colors, suggesting an indoor setting near a window. Sunlight filters in gently, creating a warm, golden tone that wraps the entire image in a sense of comfort and calm. The composition is intimate, with the puppy positioned centrally and framed by the curved edges of the basket. The sharp focus on the puppy's eyes and whiskers contrasts with the gentle blur of the surroundings, drawing the viewer's attention directly to its adorable face. Overall, the image captures a perfect blend of innocence, warmth, and charm.",
    "The image is a close-up photograph of a Shiba Inu sitting proudly in a park. Its reddish-brown fur glows warmly under the afternoon sunlight, and its coat appears impeccably groomed. The dog’s almond-shaped eyes are alert yet friendly, and its triangular ears stand upright, giving it a confident appearance. Its mouth is slightly curved into what seems like a natural smile, and its fluffy tail curls neatly over its back. The background consists of a carpet of fallen cherry blossom petals, creating a delicate pink and white texture that contrasts beautifully with the dog’s vibrant coat. A shallow depth of field blurs the distant park benches and trees, keeping the focus entirely on the Shiba Inu. The lighting is bright but soft, enhancing the warmth of the scene without harsh shadows. The composition style is balanced and centered, giving a formal portrait feel while still capturing the relaxed nature of the dog. The colors are vivid, with warm tones dominating and pastel accents adding a gentle harmony. Overall, the photograph conveys a sense of pride, beauty, and serenity.",
    "The image is a photograph of a sleepy beagle resting on a soft plaid blanket. The beagle’s tri-colored coat of white, brown, and black is short but sleek, with the brown patches glowing warmly in the afternoon light. Its long ears drape across the blanket, and its eyes are half-closed in a peaceful, drowsy expression. Its body is curled slightly, with its nose tucked close to its front paws. The blanket is a mix of earthy reds and soft creams, adding to the cozy atmosphere. The background is softly blurred, with hints of a fireplace and a wooden floor, suggesting an indoor setting on a chilly day. The lighting is warm and subdued, creating a soft glow that emphasizes the beagle’s fur texture. The composition style is intimate and comforting, with the dog filling most of the frame. The focus is crisp on the beagle’s face, while the blanket and background fade gently into softness. Overall, the image exudes a sense of calm, warmth, and homey tranquility.",
]
prompts_to_parquet(prompts, 'dog.parquet')